spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    name: defaultDataSource
    url: jdbc:mysql://localhost:3306/blue?serverTimezone=UTC
    username: '***'
    password: '***'
dubbo:
  application:
    logger: slf4j
    name: ProductApplication
  registry:
    address: nacos://${nacos.address:127.0.0.1}:8848
  protocol:
    name: tri
    port: 50051
server:
  port: 8080
