server:
  port: 8083


spring:
  datasource:
    url: jdbc:mysql://localhost:3306/dyds?serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis-plus:
  mapper-locations: classpath*:mapper/**/*.xml
  type-aliases-package: com.example.order.entity
dubbo:
  application:
    name: order-service
  registry:
    address: nacos://127.0.0.1:8848
  protocol:
    name: tri
    port: 50053

jpa:
hibernate:
ddl-auto: validate
properties:
dialect: org.hibernate.dialect.MySQL8Dialect
format_sql: true